# Generated by Django 4.2.28 on 2026-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
