# Generated by Django 4.2.28 on 2026-02-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_order_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='order_by',
            new_name='salesman',
        ),
    ]
