# Generated by Django 4.2.28 on 2026-02-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_invoice_date_invoice_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='salesman',
        ),
    ]
