# Generated by Django 4.2.28 on 2026-02-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_remove_invoice_invoice_date_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='salesman',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
