# Generated by Django 4.2.28 on 2026-02-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0010_alter_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='salesman',
        ),
    ]
